service: areac

provider:
  name: aws
  runtime: nodejs6.10

functions:
  is-areac-active-today:
    handler: src/handlers/handler.isAreaCActiveToday
    events:
      - http:
          path: is-areac-active-today
          method: get
          cors: true
